# Generated by Django 2.0.7 on 2018-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
