# Generated by Django 2.1.4 on 2018-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('create_time', models.DateField()),
            ],
        ),
    ]
